// Code generated by ogen, DO NOT EDIT.

package firefly

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// FireflyIiiAuth provides firefly_iii_auth security value.
	// Default OAuth2 flow.
	FireflyIiiAuth(ctx context.Context, operationName string) (FireflyIiiAuth, error)
}

func (s *Client) securityFireflyIiiAuth(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.FireflyIiiAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"FireflyIiiAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
