// Code generated by ogen, DO NOT EDIT.

package firefly

// setDefaults set default value of fields.
func (s *Account) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeNetWorth.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AccountStore) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeNetWorth.SetTo(val)
	}
	{
		val := string("0")
		s.Interest.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AccountUpdate) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeNetWorth.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Currency) setDefaults() {
	{
		val := bool(true)
		s.Enabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CurrencyStore) setDefaults() {
	{
		val := bool(true)
		s.Enabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Rule) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.StopProcessing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RuleAction) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.StopProcessing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RuleActionStore) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.StopProcessing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RuleStore) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(true)
		s.Strict.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RuleTrigger) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.StopProcessing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RuleTriggerStore) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.StopProcessing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RuleUpdate) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.StopProcessing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransactionStore) setDefaults() {
	{
		val := bool(true)
		s.FireWebhooks.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TransactionUpdate) setDefaults() {
	{
		val := bool(true)
		s.FireWebhooks.SetTo(val)
	}
}
