// Code generated by ogen, DO NOT EDIT.
package firefly

type BulkUpdateTransactionsRes interface {
	bulkUpdateTransactionsRes()
}

type DefaultCurrencyRes interface {
	defaultCurrencyRes()
}

type DeleteAccountRes interface {
	deleteAccountRes()
}

type DeleteAttachmentRes interface {
	deleteAttachmentRes()
}

type DeleteBillRes interface {
	deleteBillRes()
}

type DeleteBudgetLimitRes interface {
	deleteBudgetLimitRes()
}

type DeleteBudgetRes interface {
	deleteBudgetRes()
}

type DeleteCategoryRes interface {
	deleteCategoryRes()
}

type DeleteCurrencyRes interface {
	deleteCurrencyRes()
}

type DeleteLinkTypeRes interface {
	deleteLinkTypeRes()
}

type DeleteObjectGroupRes interface {
	deleteObjectGroupRes()
}

type DeletePiggyBankRes interface {
	deletePiggyBankRes()
}

type DeleteRecurrenceRes interface {
	deleteRecurrenceRes()
}

type DeleteRuleGroupRes interface {
	deleteRuleGroupRes()
}

type DeleteRuleRes interface {
	deleteRuleRes()
}

type DeleteTagRes interface {
	deleteTagRes()
}

type DeleteTransactionJournalRes interface {
	deleteTransactionJournalRes()
}

type DeleteTransactionLinkRes interface {
	deleteTransactionLinkRes()
}

type DeleteTransactionRes interface {
	deleteTransactionRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type DeleteWebhookMessageAttemptRes interface {
	deleteWebhookMessageAttemptRes()
}

type DeleteWebhookMessageRes interface {
	deleteWebhookMessageRes()
}

type DeleteWebhookRes interface {
	deleteWebhookRes()
}

type DestroyDataRes interface {
	destroyDataRes()
}

type DisableCurrencyRes interface {
	disableCurrencyRes()
}

type DownloadAttachmentRes interface {
	downloadAttachmentRes()
}

type EnableCurrencyRes interface {
	enableCurrencyRes()
}

type ExportAccountsRes interface {
	exportAccountsRes()
}

type ExportBillsRes interface {
	exportBillsRes()
}

type ExportBudgetsRes interface {
	exportBudgetsRes()
}

type ExportCategoriesRes interface {
	exportCategoriesRes()
}

type ExportPiggiesRes interface {
	exportPiggiesRes()
}

type ExportRecurringRes interface {
	exportRecurringRes()
}

type ExportRulesRes interface {
	exportRulesRes()
}

type ExportTagsRes interface {
	exportTagsRes()
}

type ExportTransactionsRes interface {
	exportTransactionsRes()
}

type FireRuleGroupRes interface {
	fireRuleGroupRes()
}

type FireRuleRes interface {
	fireRuleRes()
}

type GetAboutRes interface {
	getAboutRes()
}

type GetAccountRes interface {
	getAccountRes()
}

type GetAccountsACRes interface {
	getAccountsACRes()
}

type GetAttachmentRes interface {
	getAttachmentRes()
}

type GetAvailableBudgetRes interface {
	getAvailableBudgetRes()
}

type GetBasicSummaryRes interface {
	getBasicSummaryRes()
}

type GetBillRes interface {
	getBillRes()
}

type GetBillsACRes interface {
	getBillsACRes()
}

type GetBudgetLimitRes interface {
	getBudgetLimitRes()
}

type GetBudgetRes interface {
	getBudgetRes()
}

type GetBudgetsACRes interface {
	getBudgetsACRes()
}

type GetCategoriesACRes interface {
	getCategoriesACRes()
}

type GetCategoryRes interface {
	getCategoryRes()
}

type GetChartAccountOverviewRes interface {
	getChartAccountOverviewRes()
}

type GetConfigurationRes interface {
	getConfigurationRes()
}

type GetCronRes interface {
	getCronRes()
}

type GetCurrenciesACRes interface {
	getCurrenciesACRes()
}

type GetCurrenciesCodeACRes interface {
	getCurrenciesCodeACRes()
}

type GetCurrencyRes interface {
	getCurrencyRes()
}

type GetCurrentUserRes interface {
	getCurrentUserRes()
}

type GetDefaultCurrencyRes interface {
	getDefaultCurrencyRes()
}

type GetLinkTypeRes interface {
	getLinkTypeRes()
}

type GetObjectGroupRes interface {
	getObjectGroupRes()
}

type GetObjectGroupsACRes interface {
	getObjectGroupsACRes()
}

type GetPiggiesACRes interface {
	getPiggiesACRes()
}

type GetPiggiesBalanceACRes interface {
	getPiggiesBalanceACRes()
}

type GetPiggyBankRes interface {
	getPiggyBankRes()
}

type GetPreferenceRes interface {
	getPreferenceRes()
}

type GetRecurrenceRes interface {
	getRecurrenceRes()
}

type GetRecurringACRes interface {
	getRecurringACRes()
}

type GetRuleGroupRes interface {
	getRuleGroupRes()
}

type GetRuleGroupsACRes interface {
	getRuleGroupsACRes()
}

type GetRuleRes interface {
	getRuleRes()
}

type GetRulesACRes interface {
	getRulesACRes()
}

type GetSingleConfigurationRes interface {
	getSingleConfigurationRes()
}

type GetSingleWebhookMessageAttemptRes interface {
	getSingleWebhookMessageAttemptRes()
}

type GetSingleWebhookMessageRes interface {
	getSingleWebhookMessageRes()
}

type GetTagACRes interface {
	getTagACRes()
}

type GetTagRes interface {
	getTagRes()
}

type GetTransactionByJournalRes interface {
	getTransactionByJournalRes()
}

type GetTransactionLinkRes interface {
	getTransactionLinkRes()
}

type GetTransactionRes interface {
	getTransactionRes()
}

type GetTransactionTypesACRes interface {
	getTransactionTypesACRes()
}

type GetTransactionsACRes interface {
	getTransactionsACRes()
}

type GetTransactionsIDACRes interface {
	getTransactionsIDACRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetWebhookMessageAttemptsRes interface {
	getWebhookMessageAttemptsRes()
}

type GetWebhookMessagesRes interface {
	getWebhookMessagesRes()
}

type GetWebhookRes interface {
	getWebhookRes()
}

type InsightExpenseAssetRes interface {
	insightExpenseAssetRes()
}

type InsightExpenseBillRes interface {
	insightExpenseBillRes()
}

type InsightExpenseBudgetRes interface {
	insightExpenseBudgetRes()
}

type InsightExpenseCategoryRes interface {
	insightExpenseCategoryRes()
}

type InsightExpenseExpenseRes interface {
	insightExpenseExpenseRes()
}

type InsightExpenseNoBillRes interface {
	insightExpenseNoBillRes()
}

type InsightExpenseNoBudgetRes interface {
	insightExpenseNoBudgetRes()
}

type InsightExpenseNoCategoryRes interface {
	insightExpenseNoCategoryRes()
}

type InsightExpenseNoTagRes interface {
	insightExpenseNoTagRes()
}

type InsightExpenseTagRes interface {
	insightExpenseTagRes()
}

type InsightExpenseTotalRes interface {
	insightExpenseTotalRes()
}

type InsightIncomeAssetRes interface {
	insightIncomeAssetRes()
}

type InsightIncomeCategoryRes interface {
	insightIncomeCategoryRes()
}

type InsightIncomeNoCategoryRes interface {
	insightIncomeNoCategoryRes()
}

type InsightIncomeNoTagRes interface {
	insightIncomeNoTagRes()
}

type InsightIncomeRevenueRes interface {
	insightIncomeRevenueRes()
}

type InsightIncomeTagRes interface {
	insightIncomeTagRes()
}

type InsightIncomeTotalRes interface {
	insightIncomeTotalRes()
}

type InsightTransferCategoryRes interface {
	insightTransferCategoryRes()
}

type InsightTransferNoCategoryRes interface {
	insightTransferNoCategoryRes()
}

type InsightTransferNoTagRes interface {
	insightTransferNoTagRes()
}

type InsightTransferTagRes interface {
	insightTransferTagRes()
}

type InsightTransferTotalRes interface {
	insightTransferTotalRes()
}

type InsightTransfersRes interface {
	insightTransfersRes()
}

type ListAccountByCurrencyRes interface {
	listAccountByCurrencyRes()
}

type ListAccountRes interface {
	listAccountRes()
}

type ListAttachmentByAccountRes interface {
	listAttachmentByAccountRes()
}

type ListAttachmentByBillRes interface {
	listAttachmentByBillRes()
}

type ListAttachmentByBudgetRes interface {
	listAttachmentByBudgetRes()
}

type ListAttachmentByCategoryRes interface {
	listAttachmentByCategoryRes()
}

type ListAttachmentByPiggyBankRes interface {
	listAttachmentByPiggyBankRes()
}

type ListAttachmentByTagRes interface {
	listAttachmentByTagRes()
}

type ListAttachmentByTransactionRes interface {
	listAttachmentByTransactionRes()
}

type ListAttachmentRes interface {
	listAttachmentRes()
}

type ListAvailableBudgetByCurrencyRes interface {
	listAvailableBudgetByCurrencyRes()
}

type ListAvailableBudgetRes interface {
	listAvailableBudgetRes()
}

type ListBillByCurrencyRes interface {
	listBillByCurrencyRes()
}

type ListBillByObjectGroupRes interface {
	listBillByObjectGroupRes()
}

type ListBillRes interface {
	listBillRes()
}

type ListBudgetLimitByBudgetRes interface {
	listBudgetLimitByBudgetRes()
}

type ListBudgetLimitByCurrencyRes interface {
	listBudgetLimitByCurrencyRes()
}

type ListBudgetLimitRes interface {
	listBudgetLimitRes()
}

type ListBudgetRes interface {
	listBudgetRes()
}

type ListCategoryRes interface {
	listCategoryRes()
}

type ListCurrencyRes interface {
	listCurrencyRes()
}

type ListEventByPiggyBankRes interface {
	listEventByPiggyBankRes()
}

type ListEventByTransactionRes interface {
	listEventByTransactionRes()
}

type ListLinkTypeRes interface {
	listLinkTypeRes()
}

type ListLinksByJournalRes interface {
	listLinksByJournalRes()
}

type ListObjectGroupsRes interface {
	listObjectGroupsRes()
}

type ListPiggyBankByAccountRes interface {
	listPiggyBankByAccountRes()
}

type ListPiggyBankByObjectGroupRes interface {
	listPiggyBankByObjectGroupRes()
}

type ListPiggyBankRes interface {
	listPiggyBankRes()
}

type ListPreferenceRes interface {
	listPreferenceRes()
}

type ListRecurrenceByCurrencyRes interface {
	listRecurrenceByCurrencyRes()
}

type ListRecurrenceRes interface {
	listRecurrenceRes()
}

type ListRuleByBillRes interface {
	listRuleByBillRes()
}

type ListRuleByCurrencyRes interface {
	listRuleByCurrencyRes()
}

type ListRuleByGroupRes interface {
	listRuleByGroupRes()
}

type ListRuleGroupRes interface {
	listRuleGroupRes()
}

type ListRuleRes interface {
	listRuleRes()
}

type ListTagRes interface {
	listTagRes()
}

type ListTransactionByAccountRes interface {
	listTransactionByAccountRes()
}

type ListTransactionByBillRes interface {
	listTransactionByBillRes()
}

type ListTransactionByBudgetLimitRes interface {
	listTransactionByBudgetLimitRes()
}

type ListTransactionByBudgetRes interface {
	listTransactionByBudgetRes()
}

type ListTransactionByCategoryRes interface {
	listTransactionByCategoryRes()
}

type ListTransactionByCurrencyRes interface {
	listTransactionByCurrencyRes()
}

type ListTransactionByLinkTypeRes interface {
	listTransactionByLinkTypeRes()
}

type ListTransactionByRecurrenceRes interface {
	listTransactionByRecurrenceRes()
}

type ListTransactionByTagRes interface {
	listTransactionByTagRes()
}

type ListTransactionLinkRes interface {
	listTransactionLinkRes()
}

type ListTransactionRes interface {
	listTransactionRes()
}

type ListUserRes interface {
	listUserRes()
}

type ListWebhookRes interface {
	listWebhookRes()
}

type PurgeDataRes interface {
	purgeDataRes()
}

type SearchAccountsRes interface {
	searchAccountsRes()
}

type SearchTransactionsRes interface {
	searchTransactionsRes()
}

type SetConfigurationRes interface {
	setConfigurationRes()
}

type StoreAccountRes interface {
	storeAccountRes()
}

type StoreAttachmentRes interface {
	storeAttachmentRes()
}

type StoreBillRes interface {
	storeBillRes()
}

type StoreBudgetLimitRes interface {
	storeBudgetLimitRes()
}

type StoreBudgetRes interface {
	storeBudgetRes()
}

type StoreCategoryRes interface {
	storeCategoryRes()
}

type StoreCurrencyRes interface {
	storeCurrencyRes()
}

type StoreLinkTypeRes interface {
	storeLinkTypeRes()
}

type StorePiggyBankRes interface {
	storePiggyBankRes()
}

type StorePreferenceRes interface {
	storePreferenceRes()
}

type StoreRecurrenceRes interface {
	storeRecurrenceRes()
}

type StoreRuleGroupRes interface {
	storeRuleGroupRes()
}

type StoreRuleRes interface {
	storeRuleRes()
}

type StoreTagRes interface {
	storeTagRes()
}

type StoreTransactionLinkRes interface {
	storeTransactionLinkRes()
}

type StoreTransactionRes interface {
	storeTransactionRes()
}

type StoreUserRes interface {
	storeUserRes()
}

type StoreWebhookRes interface {
	storeWebhookRes()
}

type SubmitWebookRes interface {
	submitWebookRes()
}

type TestRuleGroupRes interface {
	testRuleGroupRes()
}

type TestRuleRes interface {
	testRuleRes()
}

type UpdateAccountRes interface {
	updateAccountRes()
}

type UpdateAttachmentRes interface {
	updateAttachmentRes()
}

type UpdateBillRes interface {
	updateBillRes()
}

type UpdateBudgetLimitRes interface {
	updateBudgetLimitRes()
}

type UpdateBudgetRes interface {
	updateBudgetRes()
}

type UpdateCategoryRes interface {
	updateCategoryRes()
}

type UpdateCurrencyRes interface {
	updateCurrencyRes()
}

type UpdateLinkTypeRes interface {
	updateLinkTypeRes()
}

type UpdateObjectGroupRes interface {
	updateObjectGroupRes()
}

type UpdatePiggyBankRes interface {
	updatePiggyBankRes()
}

type UpdatePreferenceRes interface {
	updatePreferenceRes()
}

type UpdateRecurrenceRes interface {
	updateRecurrenceRes()
}

type UpdateRuleGroupRes interface {
	updateRuleGroupRes()
}

type UpdateRuleRes interface {
	updateRuleRes()
}

type UpdateTagRes interface {
	updateTagRes()
}

type UpdateTransactionLinkRes interface {
	updateTransactionLinkRes()
}

type UpdateTransactionRes interface {
	updateTransactionRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UpdateWebhookRes interface {
	updateWebhookRes()
}

type UploadAttachmentRes interface {
	uploadAttachmentRes()
}
