#!/bin/sh

trap 'kill $(jobs -p)' TERM

CHROMEDRIVER_PORT=4444
CHROMEDRIVER_URL_BASE=wd/hub

chromedriver --port=$CHROMEDRIVER_PORT --url-base=$CHROMEDRIVER_URL_BASE --silent 2>&1 > /dev/null &
hoarder $* --tinkoff.selenium.enabled --tinkoff.selenium.browser=chromium --tinkoff.selenium.binary=$(which chromium) --tinkoff.selenium.urlPrefix=http://localhost:$CHROMEDRIVER_PORT/$CHROMEDRIVER_URL_BASE &

HOARDER=$!
wait "$HOARDER"
exit $?
