additionalProperties: false
properties:
  $schema:
    default: https://raw.githubusercontent.com/jfk9w/hoarder/master/config/schema.yaml
    type: string
  captcha:
    additionalProperties: false
    description: Настройки для решения капчи.
    properties:
      rucaptchaKey:
        description: API-ключ для сервиса rucaptcha.com.
        type: string
    type: object
  dump:
    additionalProperties: false
    description: |-
      Вывод параметров конфигурации в стандартный поток вывода.
      Предназначены для использования как CLI-параметры.
    properties:
      schema:
        description: Вывод схемы конфигурации в YAML.
        type: boolean
      values:
        description: Вывод значений конфигурации по умолчанию в JSON.
        type: boolean
    type: object
  lkdr:
    additionalProperties: false
    description: Настройка пайплана для сервиса ФНС "Мои чеки онлайн".
    properties:
      batchSize:
        default: 1000
        description: Количество чеков в одном запросе и количество фискальных данных за одно обновление.
        type: integer
      db:
        additionalProperties: false
        description: Настройки подключения к БД.
        properties:
          driver:
            enum:
              - mysql
              - postgres
              - sqlite
            type: string
          dsn:
            examples:
              - file::memory:?cache=shared
              - host=localhost port=5432 user=postgres password=postgres dbname=postgres
            type: string
        required:
          - driver
          - dsn
        type: object
      timeout:
        default: 5m0s
        description: Таймаут для запросов.
        pattern: (\d+h)?(\d+m)?(\d+s)?(\d+ms)?(\d+µs)?(\d+ns)?
        type: string
      users:
        additionalProperties:
          items:
            additionalProperties: false
            properties:
              deviceId:
                description: |-
                  Используется для авторизации и обновления токена доступа.
                  При отсутствии генерируется автоматически из userAgent и номера телефона.
                  Можно подсмотреть в браузере при попытке авторизации.
                  Обратите внимание, что токены доступа привязаны к deviceId. При смене deviceId потребуется авторизоваться заново.
                type: string
              phone:
                description: Номер телефона пользователя.
                pattern: 7\d{10}
                type: string
              userAgent:
                default: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
                description: |-
                  Используется для авторизации и обновления токена доступа.
                  Можно подсмотреть в браузере при попытке авторизации.
                type: string
            required:
              - phone
            type: object
          type: array
        description: Пользователи и их авторизационные данные.
        type: object
    required:
      - db
      - users
    type: object
  log:
    additionalProperties: false
    description: Настройки логирования для библиотеки slog.
    properties:
      addSource:
        description: Добавлять ли номера строк в логи.
        type: boolean
      encoding:
        default: text
        description: Формат логирования.
        enum:
          - text
          - json
        type: string
      level:
        default: INFO
        description: Уровень логирования.
        enum:
          - DEBUG
          - INFO
          - WARN
          - ERROR
        type: string
    type: object
  schedule:
    additionalProperties: false
    description: Настройки фоновой синхронизации.
    properties:
      interval:
        default: 30m0s
        description: Интервал синхронизации.
        pattern: (\d+h)?(\d+m)?(\d+s)?(\d+ms)?(\d+µs)?(\d+ns)?
        type: string
      users:
        description: Пользователи, для которых данные нужно синхронизировать в фоновом режиме.
        items:
          type: string
        type: array
    required:
      - users
    type: object
  stdin:
    description: Включение интерактивной командной строки.
    type: boolean
  tinkoff:
    additionalProperties: false
    description: Настройка пайплайна для онлайн-банка "Тинькофф".
    properties:
      batchSize:
        default: 100
        description: Максимальный размер батчей.
        type: integer
      db:
        additionalProperties: false
        description: Настройки подключения к БД.
        properties:
          driver:
            enum:
              - mysql
              - postgres
              - sqlite
            type: string
          dsn:
            examples:
              - file::memory:?cache=shared
              - host=localhost port=5432 user=postgres password=postgres dbname=postgres
            type: string
        required:
          - driver
          - dsn
        type: object
      disableReceipts:
        description: Отключить синхронизацию чеков.
        type: boolean
      overlap:
        default: 168h0m0s
        description: Продолжительность "нахлеста" при обновлении операций.
        pattern: (\d+h)?(\d+m)?(\d+s)?(\d+ms)?(\d+µs)?(\d+ns)?
        type: string
      users:
        additionalProperties:
          items:
            additionalProperties: false
            properties:
              password:
                description: Пароль от аккаунта Тинькофф.
                type: string
              phone:
                description: Номер телефона, на который зарегистрирован аккаунт Тинькофф.
                pattern: 7\d{10}
                type: string
            required:
              - phone
              - password
            type: object
          type: array
        description: Пользователи и их авторизационные данные.
        type: object
    required:
      - db
      - users
    type: object
  xmpp:
    additionalProperties: false
    description: Настройки XMPP-интерфейса.
    properties:
      jid:
        description: Jabber ID для бота.
        type: string
      password:
        description: Пароль для бота.
        type: string
      users:
        additionalProperties:
          type: string
        description: Маппинг JID в имя пользователя, используемое в пайплайнах.
        type: object
    required:
      - jid
      - password
      - users
    type: object
type: object
