additionalProperties: false
properties:
  $schema:
    default: https://raw.githubusercontent.com/jfk9w/hoarder/master/config/schema.yaml
    type: string
  captcha:
    additionalProperties: false
    description: Настройки для решения капчи.
    properties:
      rucaptchaKey:
        description: API-ключ для сервиса rucaptcha.com.
        type: string
    type: object
  dump:
    additionalProperties: false
    description: |-
      Вывод параметров конфигурации в стандартный поток вывода.
      Предназначены для использования как CLI-параметры.
    properties:
      schema:
        description: Вывод схемы конфигурации в YAML.
        type: boolean
      values:
        description: Вывод значений конфигурации по умолчанию в JSON.
        type: boolean
    type: object
  lkdr:
    additionalProperties: false
    description: Настройка загрузчиков из сервиса ФНС "Мои чеки онлайн".
    properties:
      batchSize:
        default: 1000
        description: Количество чеков в одном запросе и количество фискальных данных за одно обновление.
        type: integer
      db:
        additionalProperties: false
        description: Настройки подключения к БД.
        properties:
          driver:
            enum:
              - postgres
              - mysql
              - sqlite
            type: string
          dsn:
            examples:
              - file::memory:?cache=shared
            type: string
        required:
          - driver
          - dsn
        type: object
      deviceId:
        description: |-
          Используется для авторизации и обновления токена доступа.
          Можно подсмотреть в браузере при попытке авторизации.
        type: string
      init:
        description: Пользователь, для которого нужно провести инициализацию.
        type: string
      userAgent:
        description: |-
          Используется для авторизации и обновления токена доступа.
          Можно подсмотреть в браузере при попытке авторизации.
        type: string
      users:
        additionalProperties:
          items:
            additionalProperties: false
            properties:
              phone:
                description: Номер телефона пользователя.
                pattern: 7\d{10}
                type: string
            required:
              - phone
            type: object
          type: array
        description: Пользователи и их авторизационные данные.
        type: object
    required:
      - db
      - deviceId
      - userAgent
      - users
    type: object
type: object
