additionalProperties: false
properties:
  $schema:
    default: https://raw.githubusercontent.com/jfk9w/hoarder/master/config/schema.yaml
    type: string
  captcha:
    additionalProperties: false
    description: Настройки для решения капчи.
    properties:
      rucaptchaKey:
        description: API-ключ для сервиса rucaptcha.com.
        type: string
    type: object
  dump:
    additionalProperties: false
    description: |-
      Вывод параметров конфигурации в стандартный поток вывода.
      Предназначены для использования как CLI-параметры.
    properties:
      schema:
        description: Вывод схемы конфигурации в YAML.
        type: boolean
      values:
        description: Вывод значений конфигурации по умолчанию в JSON.
        type: boolean
    type: object
  firefly:
    additionalProperties: false
    description: Настройки подключения к Firefly III.
    properties:
      accessToken:
        description: Персональный токен доступа.
        type: string
      serverUrl:
        description: URL сервера Firefly III.
        type: string
    required:
      - serverUrl
      - accessToken
    type: object
  log:
    additionalProperties: false
    description: Настройки логирования для библиотеки slog.
    properties:
      addSource:
        description: Добавлять ли номера строк в логи.
        type: boolean
      encoding:
        default: text
        description: Формат логирования.
        enum:
          - text
          - json
        type: string
      level:
        default: INFO
        description: Уровень логирования.
        enum:
          - DEBUG
          - INFO
          - WARN
          - ERROR
        type: string
    type: object
  schedule:
    additionalProperties: false
    description: Настройки фоновой синхронизации.
    properties:
      interval:
        default: 30m0s
        description: Интервал синхронизации.
        pattern: (\d+h)?(\d+m)?(\d+s)?(\d+ms)?(\d+µs)?(\d+ns)?
        type: string
      users:
        additionalProperties:
          items:
            type: string
          type: array
        description: ID пользователей, для которых данные нужно синхронизировать в фоновом режиме.
        type: object
    required:
      - users
    type: object
  stdin:
    description: Включение интерактивной командной строки.
    type: boolean
  tinkoff:
    additionalProperties: false
    description: Настройка пайплайна для онлайн-банка "Тинькофф".
    properties:
      batchSize:
        default: 100
        description: Максимальный размер батчей.
        type: integer
      database:
        additionalProperties: false
        description: Настройки подключения к БД.
        properties:
          driver:
            enum:
              - mysql
              - postgres
              - sqlite
            type: string
          dsn:
            examples:
              - file::memory:?cache=shared
              - host=localhost port=5432 user=postgres password=postgres dbname=postgres search_path=public
            type: string
        required:
          - driver
          - dsn
        type: object
      overlap:
        default: 168h0m0s
        description: Продолжительность "нахлеста" при обновлении операций.
        pattern: (\d+h)?(\d+m)?(\d+s)?(\d+ms)?(\d+µs)?(\d+ns)?
        type: string
      users:
        additionalProperties:
          items:
            additionalProperties: false
            properties:
              password:
                description: Пароль от аккаунта Тинькофф.
                type: string
              phone:
                description: Номер телефона, на который зарегистрирован аккаунт Тинькофф.
                pattern: 7\d{10}
                type: string
            required:
              - phone
              - password
            type: object
          type: array
        description: Пользователи и их авторизационные данные.
        type: object
      withReceipts:
        default: true
        description: Включить синхронизацию чеков.
        type: boolean
    required:
      - database
      - users
    type: object
  xmpp:
    additionalProperties: false
    description: Настройки XMPP-триггера.
    properties:
      jid:
        description: JID бота.
        type: string
      password:
        description: Пароль.
        type: string
      presence:
        default: 1m0s
        description: Интервал для отправки присутствия.
        pattern: (\d+h)?(\d+m)?(\d+s)?(\d+ms)?(\d+µs)?(\d+ns)?
        type: string
      state:
        default: 5s
        description: Интервал для отправки состояния ("печатает").
        pattern: (\d+h)?(\d+m)?(\d+s)?(\d+ms)?(\d+µs)?(\d+ns)?
        type: string
      users:
        additionalProperties:
          type: string
        description: Маппинг JID в имя пользователя.
        type: object
    required:
      - jid
      - password
      - users
    type: object
type: object
