name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable
      - name: Build
        run: make build
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Check config schema & defaults
        run: |
          make config
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make config and commit changes'
            exit 1
          fi
      - name: Test
        run: make test
      - name: Update test coverage
        uses: ncruces/go-coverage-report@main
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: [ test ]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/} .
      - name: Publish image
        run: docker push ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/}
