name: CI

on: [ push, workflow_dispatch ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --verbose --timeout=10m
          version: latest
      - name: Build
        run: make bin
      - name: Test
        run: make test
      - name: Check config schema & defaults
        run: |
          make config
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make config and commit changes'
            exit 1
          fi
  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [ test ]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    steps:
      - uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        run: |
          PLATFORM="linux/amd64"
          if [[ "$GITHUB_REF_NAME" == "master" ]]; then
            IMAGE_TAGS="-t ghcr.io/$GITHUB_REPOSITORY:latest"
            PLATFORM="$PLATFORM,linux/arm64"
          else
            IMAGE_TAGS="-t ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF_NAME##*/}"
          fi

          docker buildx create --use
          docker buildx build . $IMAGE_TAGS --platform=$PLATFORM --push
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
