name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable
      - name: Build
        run: make build
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
      - name: Check config schema & defaults
        run: |
          make config
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make config and commit changes'
            exit 1
          fi
      - name: Test
        run: make test
      - name: Update test coverage
        uses: ncruces/go-coverage-report@main
