name: Publish Docker image

on:
  push:
    branches: [ master ]
    tags: [ '**' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build -t ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/} .
          docker push ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/}
